### ISSUE TITLE
Возможность раскрыть историю чата

### ISSUE THREAD

**Issue by ghost** [iassasin/wschatserver#16]
Вот бывает зайдешь в чат, а там такая интересная история произошла, и тут это дурацкое ограничение в 50 сообщений, и так и не узнаешь, из-за чего же получился конфликт/общение на n-ную тему.

Поэтому, предлагаю при пролистывании чата в самый верх добавить кнопку "Показать более ранние сообщения" и хранение лога чата сроком в 2 дня.

**Comment by iassasin** [comment]
Это пока достаточно сложно сделать

**Comment by ghost** [comment]
@iassasin, тогда пусть висит таск до появления возможности реализации.

**Comment by iassasin** [comment]
Противоречит основной идее чата, что история не хранится. Пока не будет реализовано.
