### ISSUE TITLE
Цитаты

### ISSUE THREAD

**Issue by Levsha1337** [iassasin/wschatserver#19]
При выделении текста появление кнопки (как на пикабу в комментариях), которая СРАЗУ перекидывает выделенный текст цитатой в поле ввода, либо просто при копировании сообщения в буфер обмена добавлять в начале "> ".

**Comment by ghost** [comment]
Предложу другой вариант: автоматически вставлять полную цитату в поле ввода при клике на время около сообщения.

**Comment by Levsha1337** [comment]
Выполнено, но не полностью. Сломано нормальное выделение и копирование для цитатника.

**Comment by iassasin** [comment]
> Предложу другой вариант: автоматически вставлять полную цитату в поле ввода при клике на время около сообщения.

Реализовано. Также если есть выделенная часть, то цитирует только ее.

> Сломано нормальное выделение и копирование для цитатника.

Не понятно, что это значит. Не воспроизводится. Копировать для цитатника можно из поля ввода.
