### ISSUE TITLE
Не устанавливаются дефолтные цвет и ник

### ISSUE THREAD

**Issue by iassasin** [iassasin/wschatserver#21]
При заходе в только что созданную комнату даже если авторизован на сайте не устанавливаются дефолтные ник и цвет.

**Comment by maestroprog** [comment]
Вроде выяснилось что это не баг, изменения в https://github.com/maestroprog/wschatserver/commit/46bf1c9eb005f8dc02fc026c3799067831d65124

**Comment by iassasin** [comment]
Не является багом, следует сделать эту фичу опцией, по выбору клиента

**Comment by maestroprog** [comment]
как в phplate - фичи-опции

**Comment by iassasin** [comment]
И все-таки баг. ~~Но фичу потом надо сделать)~~ Чего это я, фича уже есть - флаг [auto_login](https://github.com/iassasin/wschatapi/blob/master/src/packets.ts#L92)
